version: 0.2
phases:
  build:
    commands:
      - docker --version
      - server=public.ecr.aws/v6m6o3k4
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin "$server"
      - case $( uname -m ) in ( aarch64 ) arch=arm64 ;; ( x86_64 ) arch=amd64 ;; ( * ) exit 1 ;; esac
      - tag="$server/elm:$CODEBUILD_RESOLVED_SOURCE_VERSION-$arch"
      - echo "$tag"
      - docker build --tag "$tag" .
      - docker push "$tag"

# After both amd64 (x86_64) and arm64 (aarch64) builds finish, run these commands:
#
# > docker manifest create \
# >  "$server/elm:$CODEBUILD_RESOLVED_SOURCE_VERSION" \
# >  "$server/elm:$CODEBUILD_RESOLVED_SOURCE_VERSION-amd64" \
# >  "$server/elm:$CODEBUILD_RESOLVED_SOURCE_VERSION-arm64"
#
# > docker manifest push "$server/elm:$CODEBUILD_RESOLVED_SOURCE_VERSION"
#
# That will create a single manifest that contains both architectures.
